name: Deploy Application

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PROJECT_NAME: ${{startsWith(github.ref, 'refs/tags/') && 'landing-prod' || 'landing-dev'}}
  VITE_ENV: ${{startsWith(github.ref, 'refs/tags/') && vars.VITE_ENV_PROD || vars.VITE_ENV_DEV}}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploying to...
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "🚀 Starting **PRODUCTION** build and deploy..."
          else
            echo "🧪 Starting **DEVELOPMENT** build and deploy..."
          fi

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.14.4

      - name: Copy ENV
        env:
          VITE_ENV: ${{ env.VITE_ENV }}
        run: |
          echo "$VITE_ENV" > .env
          echo "VITE_RELEASE_VERSION=${{ github.ref_name }}" >> .env

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint

      - name: Build project
        run: pnpm run build

      - name: Install Wrangler
        run: pnpm install -g wrangler

      - name: Publish to Cloudflare Pages
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          wrangler pages deploy ./build/client --project-name=${{ env.PROJECT_NAME }} --branch=main
